set rtp+=~/.vim/bundle/vundle
call vundle#rc()
Bundle 'gmarik/vundle'
Bundle 'scrooloose/nerdtree'
Bundle 'mattn/emmet-vim'
Bundle 'kien/ctrlp.vim'
Bundle 'arecarn/frisk'
Bundle 'scrooloose/syntastic'

set t_Co=256
syntax on
set background=dark
colorscheme Tomorrow-Night
set number
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

" Copy to system clipboard when you yank
set clipboard=unnamed

" set leader key to comma
let mapleader = ","

" Invisible Characters
" Shortcut to rapidly toggle `set list`
nmap <leader>l :set list!<CR>
" Use the same symbols as TextMate for tabstops and EOLs
set listchars=tab:▸\ ,eol:¬

" Plugins

" NERDTree
" open NERDTree when vim starts up
" autocmd vimenter * NERDTree
" nmap <leader>n: NERDTree!<CR>
" let NERDTreeMapOpenSplit='s'
" let NERDTreeMapOpenVSplit='v'

" ctrlp
let g:ctrlp_map = '<leader>f'
