set rtp+=~/.vim/bundle/vundle
call vundle#rc()
Bundle 'gmarik/vundle'
Bundle 'scrooloose/nerdtree'

syntax on
set number
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

" Copy to system clipboard when you yank
set clipboard=unnamed

" Invisible Characters
" Shortcut to rapidly toggle `set list`
nmap <leader>l :set list!<CR>
" Use the same symbols as TextMate for tabstops and EOLs
set listchars=tab:▸\ ,eol:¬

" Plugins

" NERDTree
" open NERDTree when vim starts up
autocmd vimenter * NERDTree

colorscheme Tomorrow-Night
