#!/bin/bash

set -euo pipefail

# Ask for the administrator password upfront
sudo -v

. $HOME/settings/macos/dotfiles/.config/scripts/fancy_echo.sh

function install_xcode_command_line_tools () {
  fancy_echo 'Installing Xcode Command Line Tools'
  if pkgutil --pkg-info com.apple.pkg.CLTools_Executables >/dev/null 2>&1; then
    echo 'Already installed'
  else
    xcode-select --install
  fi
}

function install_zsh () {
  fancy_echo 'Installing zsh'
  # Test to see if zshell is installed.  If it is:
  if [ -f /bin/zsh -o -f /usr/bin/zsh ]; then
    # Set the default shell to zsh if it isn't currently set to zsh
    if [[ ! $(echo $SHELL) == $(which zsh) ]]; then
      chsh -s $(which zsh)
    fi
  else
    # If zsh isn't installed, get the platform of the current machine
    platform=$(uname);
    # If the platform is Linux, try an apt-get to install zsh and then recurse
    if [[ $platform == 'Linux' ]]; then
      sudo apt-get install zsh
      install_zsh
    # If the platform is OS X, tell the user to install zsh :)
    elif [[ $platform == 'Darwin' ]]; then
      echo "Please install zsh, then re-run this script!"
      exit
    fi
  fi
}

function install_or_update_homebrew {
  # This if statement doesn't seem to work until homebrew is installed...
  which -s brew
  if [[ $? != 0 ]] ; then
      fancy_echo 'Installing Homebrew'
      # Install Homebrew
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      sudo chown -R $(whoami) /usr/local
  else
      fancy_echo 'Updating Homebrew'
      brew update
  fi
}

function install_or_update_homebrew_package {
  if ! brew list $1 >& /dev/null; then
    brew install $1
  fi
}

function homebrew_packages {
  install_or_update_homebrew

  brew tap lucasefe/ta

  apps=$(cat ~/settings/macos/apps/homebrew_packages.txt)

  # Use Homebrew to install command line packages
  fancy_echo 'Installing Homebrew packages'
  for app in $apps; do
    install_or_update_homebrew_package $app
  done
}

function npm_packages {
  fancy_echo 'Installing npm packages'

  mkdir -p ~/.npm-global

  npm install -g n
  sudo chown -R $(whoami) /usr/local/lib/node_modules/
  n stable

  apps=$(cat ~/settings/macos/apps/npm_packages.txt)

  # Use npm to install command line apps
  for app in $apps; do
    fancy_echo $app
    npm install -g $app
  done
}

function dotfiles {
  fancy_echo 'Copying dotfiles'

  # Create dotfile symlinks in home directory
  for file in $(find ~/settings/macos/dotfiles -depth 1 -exec basename {} \;); do
    rm -rf ~/$file
    ln -s ~/settings/macos/dotfiles/$file ~/$file
  done
}

function nvim {
  fancy_echo "Installing Neovim Python Providers"

#   pip2 install --upgrade neovim
  pip3 install --upgrade neovim
}

function vim_plugins {
  fancy_echo 'Installing vim plugins'
  # Use vim-plug to install vim plugins
  vim +PlugInstall +qall
  nvim +PlugInstall +qall
}

function install_or_update_gui_app {
  if ! brew cask list $1 >& /dev/null; then
    brew cask install $1 || fancy_echo_red 'Error installing '$1
  fi
}

function gui_apps {
  fancy_echo 'Installing GUI apps'
  apps=$(cat ~/settings/macos/apps/gui_apps.txt)

  # Use Homebrew Cask to install gui apps
  for app in $apps; do
    install_or_update_gui_app $app
  done
}

function ruby {
  if ! command -v rbenv >/dev/null; then
    if ! command -v rvm >/dev/null; then
      fancy_echo 'Installing RVM and the latest Ruby...'
      curl -L https://get.rvm.io | bash -s stable --ruby --auto-dotfiles --autolibs=enable
      . ~/.rvm/scripts/rvm
    else
      local_version="$(rvm -v 2> /dev/null | awk '$2 != ""{print $2}')"
      latest_version="$(curl -s https://raw.githubusercontent.com/wayneeseguin/rvm/stable/VERSION)"
      if [ "$local_version" != "$latest_version" ]; then
        fancy_echo 'Upgrading RVM...'
        rvm get stable --auto-dotfiles --autolibs=enable --with-gems="bundler"
      else
        fancy_echo "Already using the latest version of RVM. Skipping..."
      fi
    fi
  fi
}

function install_or_update_gem {
  if gem list "$1" | grep "^$1 ("; then
    fancy_echo "Updating $1..."
    gem update "$@"
  else
    fancy_echo "Installing $1..."
    gem install "$@"
  fi
}

function ruby_gems {
  apps=$(cat ~/settings/macos/apps/ruby_gems.txt)

  fancy_echo 'Installing Ruby gems'
  for app in $apps; do
    install_or_update_gem $app
  done
}

function macos {
  fancy_echo 'Run Mac Scripts'
  ~/settings/macos/dotfiles/.config/scripts/.macos
}

function development {
  fancy_echo 'Create Development directory'
  mkdir -p ~/Development
}

function install {
  install_xcode_command_line_tools
  install_zsh
  dotfiles
  nvim
  homebrew_packages
  npm_packages
  gui_apps
  vim_plugins
  ruby
  ruby_gems
  macos
  development
}

install
